name: Vote
main: me.Signifies.Vote.Main
version: 2.0.2
description: Votifier Listener for servers.
depends: [Votifier]
softdepend: [Vault]
website: https://www.spigotmc.org/resources/vote-votifier-listener-beta.15240/
author: Signifies

commands:
  vote:
    description: Main command for Vote plugin.
